USE [Database]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [NewsFeed_StarredArticles](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NewsArticleID] [int] NOT NULL,
	[UserIPAddress] [nvarchar](25) NOT NULL,
	[DateTime] [datetime] NOT NULL,
 CONSTRAINT [PK_NewsFeed_StarredArticles] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


